// Bundled default content for the two lobby directory boards, transcribed from
// the supplied HEXA_L4_Directory.png / HEXA_L2_Directory.png.
//
// Used to pre-fill the admin editor on first load and as the display-page
// fallback before a row exists in Supabase (or before the migration is run), so
// the TV boards always render something. A `name` may contain a newline for a
// bilingual / two-tenant second line.

export const DEFAULT_BOARDS = {
  '4': {
    level: '4',
    levelLabel: 'LEVEL 4',
    address: '830 WHITEHORSE ROAD · BOX HILL',
    suites: [
      { suite: '1', name: 'GrantGuru / GrantReady' },
      { suite: '2', name: 'Simple Stacks Accounting Services' },
      { suite: '3', name: 'Melbourne Creative Group' },
      { suite: '4', name: 'Connected Logics' },
      { suite: '5', name: 'New U Life' },
      { suite: '6', name: 'WKM Consumer Brands' },
      { suite: '7', name: 'Mindmetta Counseling & Integrative Therapy\n心慈心理咨询与整合疗愈工作室' },
      { suite: '8', name: 'Simple Stacks Accounting Services' },
      { suite: '9', name: 'Digitec IT 鼎捷数字技术' },
      { suite: '10', name: 'Chethana Psychology' },
    ],
    showCommunity: true,
    communityHeading: 'COMMUNITY MEMBERS',
    communitySubheading: '六 合 空 间 · 社 区 成 员',
    community: [
      '6Homes',
      '7AM Photography Studio',
      '澳中商圈 AC Bridge International Group',
      'Ace International Property Group Pty Ltd',
      'ALLSET Conveyancing',
      'AO HUA YOU YUE Pty Ltd',
      'Astra Education & Migration Pty Ltd',
      'Aurora Migration Services',
      'Australian Building and Property Association VIC',
      'BLUEGREAT Pty Ltd',
      'Bricklane Property Group',
      'Bruce Global Taste Hub Pty Ltd',
      'Drug Advisory Council Australia',
      'Emai Accounting & BA Service',
      'Emerald Family Enterprise Group',
      'Emition Photography Studio',
      'Fureeze',
      'GOMA Commercial Services Pty Ltd',
      'Heena4BoxHill',
      'HITPOINT Pty Ltd',
      'I Do International Pty Ltd',
      'Invincible Energy',
      'JC Partners Lawyers',
      'J & H Legal Pty Ltd',
      'Joyful Living Pty Ltd',
      'Joyowo Geo Pty Ltd',
      'LM Yarra Conveyancing Pty Ltd',
      'Lunea',
      'LuxeKey Capital',
      'Lydian GBS',
      'MAI Capital Pty Ltd',
      'MEBUILD',
      'Money Chain Foreign Exchange',
      'Mynt',
      'New Bridge Edu',
      'New Route Pty Ltd',
      'New Vision Education Australia',
      'NovaFab Curtains and Blinds',
      'Ocon Project Solutions',
      'Orchardlink Pty Ltd',
      'Overallead Pty Ltd',
      'OZ-East International',
      'Pinecone Petpro Pty Ltd',
      'Proud Cactus',
      'Regent Metal Group Pty Ltd',
      'TinTax | Expert Tax & Accounting Services',
      'TJLAW Lawyers',
      'Top Trading Australia Pty Ltd',
      'Trafficon',
      'Unique Roofing & Home Improvements',
      'Verge Legal',
      'You Hao Pty Ltd',
      'Young Zhang',
      'Yuen & Z Investment Pty Ltd',
      'ZC Mortgage Solutions',
      'Zecco Property Services',
      'Zheng Hong Capital Pty Ltd',
      'Z Property International',
    ],
  },
  '2': {
    level: '2',
    levelLabel: 'LEVEL 2',
    address: '830 WHITEHORSE ROAD · BOX HILL',
    suites: [
      { suite: '1', name: 'Brixton Insurance / Prestige Car Insurance' },
      { suite: '2', name: 'Canwealth Property Group' },
      { suite: '3', name: 'PHC Accounting\nCentral Conveyancing Services' },
      { suite: '4', name: 'QBS Partners Chartered Accountants' },
      { suite: '5', name: 'JJT Finance Group' },
      { suite: '6', name: 'Raiden Centauri' },
      { suite: '7', name: 'Wehome Real Estate' },
      { suite: '8', name: 'Victor Group Holdings' },
      { suite: '9', name: 'Grand Galaxy 星空出行 & MSJ Media 禾子传媒' },
      { suite: '10', name: 'Nexus Interactive' },
      { suite: '11', name: '首选居家养老 Top 1 Care' },
      { suite: '12', name: '首选居家养老 Top 1 Care' },
      { suite: '13', name: 'Tantu' },
      { suite: '14', name: 'AJ Lee Property Group' },
      { suite: '15', name: 'Level Up | Consulting Engineers' },
      { suite: '17', name: 'Top Bridge Group 盛大移民 / 留学' },
      { suite: '18', name: 'Earth Power Co' },
      { suite: '19', name: 'PanAus Partners Melbourne' },
      { suite: '20', name: 'Sleek Circle' },
      { suite: '21', name: 'Karad & Bradley Architects & Planners' },
      { suite: '22', name: 'Brown & Turner Legal\nAzlan Lawyers' },
      { suite: '23', name: 'Masterlink Communications' },
      { suite: '24', name: 'Wehome Real Estate' },
      { suite: '25', name: 'Olivecast Podcast Studio' },
      { suite: '26', name: 'Global Link Logistics / Easy Way Logistics' },
      { suite: '27', name: 'RIO Capital' },
    ],
    showCommunity: false,
    communityHeading: 'COMMUNITY MEMBERS',
    communitySubheading: '六 合 空 间 · 社 区 成 员',
    community: [],
  },
}

// Deep-ish clone so the editor never mutates the shared default.
export function cloneBoard(level) {
  return JSON.parse(JSON.stringify(DEFAULT_BOARDS[level]))
}
